name: Facebook Live Stream

on:
  workflow_dispatch: # يسمح لك بتشغيل البث يدوياً بضغطة زر

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming to Facebook
        run: |
          ffmpeg -re -i "http://135.125.109.73:9000/Alwan%20Sport%201%20HD%20VIP%20Arb_.m3u8" \
          -c:v copy -c:a aac -strict experimental \
          -f flv "rtmps://live-api-s.facebook.com:443/rtmp/FB-122122401357122511-1-Ab6SISX3ImJQaZ_3O0hSnRDC"
